keys:
  - &date_simon age1rp02s3ay8nd4f95x7vydxddk2dtdun4jl9d5lyu0zjxuw7k8qu0q79d42q
  - &date_host  age1jtx5upe8zzlgulqadm9a083nc0tsym3jcjsujyaywaqzg398ycdqw2p67r
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini|sops)$
    key_groups:
      - age:
          - *date_simon
          - *date_host
